onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd
overrides:
  '@kixelated/hang': link:../moq/js/hang
  '@kixelated/moq': link:../moq/js/moq
  '@kixelated/signals': link:../moq/js/signals
  'tauri-plugin-web-transport': link:../tauri-plugin-web-transport
