packages:
  - .
  - app
  - api
  - moq/js/moq
  - moq/js/hang
  - moq/js/moq-token
  - moq/js/signals

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd

overrides:
  '@kixelated/hang': link:./moq/js/hang
  '@kixelated/moq': link:./moq/js/moq
  '@kixelated/moq-token': link:./moq/js/moq-token
  '@kixelated/signals': link:./moq/js/signals
