#!/usr/bin/env just --justfile

# Using Just: https://github.com/casey/just?tab=readme-ov-file#installation

# PostgreSQL data directory (persistent)
pg_data := ".pgdata"

export DATABASE_URL := "postgres:///hang?host=/tmp"
export SQLX_OFFLINE := "true"

# List all of the available commands.
default:
  just --list

# Run the CI checks
check flags="":
	cargo test --all-targets --all-features {{flags}}
	cargo clippy --all-targets --all-features {{flags}} -- -D warnings
	cargo fmt --all --check

	# requires: cargo install cargo-shear
	cargo shear

	# requires: cargo install cargo-sort
	cargo sort --workspace --check

	# requires: cargo install cargo-audit
	cargo audit

	# Make sure the database schema is up to date.
	# TODO: This requires running the database, right?
	#cargo sqlx prepare --check

# Automatically fix some issues.
fix flags="":
	cargo fix --allow-staged --all-targets --all-features {{flags}}
	cargo clippy --fix --allow-staged --all-targets --all-features {{flags}}
	cargo fmt --all

	# requires: cargo install cargo-shear
	cargo shear --fix

	# requires: cargo install cargo-sort
	cargo sort --workspace

	# requires: cargo install cargo-audit
	cargo audit

	# Update any patch versions
	cargo update

# Upgrade any tooling
upgrade:
	# Update any patch versions
	cargo update

	# Requires: cargo install cargo-upgrades cargo-edit
	cargo upgrade --incompatible

# Build the packages
build:
	cargo build

# Run the API server in the foreground.
# Use nix to install any required dependencies.
dev:
	@nix develop --command just dev-nix

dev-nix:
	@pg_ctl -D "{{pg_data}}" stop || true

	# Initialize a local PostgreSQL database if it doesn't exist.
	if [ ! -d "{{pg_data}}" ]; then \
		initdb -D "{{pg_data}}" --auth-local=trust; \
	fi

	# Start the database in the background.
	pg_ctl -D "{{pg_data}}" -w start

	# Create the database (if it doesn't exist).
	sqlx database create

	# Run any pending migrations.
	sqlx migrate run

	# Save the database schema so we can build without the database running.
	cargo sqlx prepare

	# Run the API server.
	cargo run -- dev.toml