#!/usr/bin/env just --justfile

# Using Just: https://github.com/casey/just?tab=readme-ov-file#installation

# PostgreSQL data directory (persistent)
pg_data := ".pgdata"

export RUST_BACKTRACE := "1"
export RUST_LOG := "debug"

# List all of the available commands.
default:
  just --list

# Reinitialize everything and install any dependencies.
setup:
	# Stop the database if it's running.
	if [ -d "{{pg_data}}" ]; then \
		pg_ctl -D "{{pg_data}}" -w stop || true; \
		rm -rf "{{pg_data}}"; \
	fi

	# Create a new database.
	initdb -D "{{pg_data}}" --auth-local=trust; \

	# Start/migrate the database.
	just db

# Start/migrate the database.
db:
	# Start the database in the background if needed
	if ! pg_ctl -D "{{pg_data}}" status > /dev/null 2>&1; then \
		pg_ctl -D "{{pg_data}}" -w start; \
	fi

	# Create the database (if it doesn't exist).
	sqlx database create

	# Run any pending migrations.
	sqlx migrate run

	# Save the database schema so we can build without the database running.
	cargo sqlx prepare

# Run the CI checks
check flags="":
	cargo test --all-targets --all-features {{flags}}
	cargo clippy --all-targets --all-features {{flags}} -- -D warnings
	cargo fmt --all --check

	# requires: cargo install cargo-shear
	cargo shear

	# requires: cargo install cargo-sort
	cargo sort --workspace --check

	# requires: cargo install cargo-audit
	cargo audit

	# Make sure the database schema is up to date.
	# TODO: This requires running the database, right?
	#cargo sqlx prepare --check

# Automatically fix some issues.
fix flags="":
	cargo fix --allow-staged --all-targets --all-features {{flags}}
	cargo clippy --fix --allow-staged --all-targets --all-features {{flags}}
	cargo fmt --all

	# requires: cargo install cargo-shear
	cargo shear --fix

	# requires: cargo install cargo-sort
	cargo sort --workspace

	# requires: cargo install cargo-audit
	cargo audit

	# Update any patch versions
	cargo update

# Upgrade any tooling
upgrade:
	# Update any patch versions
	cargo update

	# Requires: cargo install cargo-upgrades cargo-edit
	cargo upgrade --incompatible

# Build the packages
build:
	cargo build

# Run the API server in the foreground.
dev: db
	# Run the API server.
	cargo run -- dev.toml
