// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountAvatar = { url: string, };

export type AccountInfo = { id: string, name: string, avatar: string, };

export type AccountUpdate = { name?: string, avatar?: string, };

export type AuthProviders = { names: Array<string>, };

export type Health = { status: string, timestamp: string, version: string, };
