import { mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import * as Token from "@moq/token";
import { z } from "zod";

const urlSchema = z.string().url();
const configuredString = z
	.string()
	.trim()
	.min(1)
	.refine((value) => !value.startsWith("replace-with-"), "must be configured; replace the example placeholder");
const authSecret = configuredString.min(32, "must be at least 32 characters");
const relaySecret = configuredString.refine(
	(value) => {
		try {
			Token.load(value);
			return true;
		} catch {
			return false;
		}
	},
	"must be a base64url-encoded JWK generated by @moq/token",
);

const nodeEnvSchema = z.object({
	API_URL: urlSchema,
	APP_URL: urlSchema,
	GOOGLE_CLIENT_ID: configuredString,
	DISCORD_CLIENT_ID: configuredString,
	R2_PUBLIC_URL: urlSchema,
	RELAY_URL: urlSchema,
	RELAY_PREFIX: configuredString,
	APPLE_CLIENT_ID: configuredString,
	APPLE_TEAM_ID: configuredString,
	APPLE_KEY_ID: configuredString,
	AUTH_SECRET: authSecret,
	GOOGLE_CLIENT_SECRET: configuredString,
	DISCORD_CLIENT_SECRET: configuredString,
	APPLE_CLIENT_SECRET: configuredString,
	RELAY_SECRET: relaySecret,
	DATABASE_PATH: configuredString,
	PUBLIC_STORAGE_PATH: configuredString,
	PORT: z.coerce.number().int().positive().default(3000),
});

export type RuntimeEnv = z.infer<typeof nodeEnvSchema> & {
	DB?: D1Database;
	PUBLIC?: R2Bucket;
};

export function loadNodeEnv(source: NodeJS.ProcessEnv = process.env): RuntimeEnv {
	const parsed = nodeEnvSchema.safeParse(source);
	if (!parsed.success) {
		const messages = parsed.error.issues.map((issue) => `${issue.path.join(".")}: ${issue.message}`);
		throw new Error(`Invalid API configuration:\n${messages.join("\n")}`);
	}

	const env = {
		...parsed.data,
		DATABASE_PATH: resolve(parsed.data.DATABASE_PATH),
		PUBLIC_STORAGE_PATH: resolve(parsed.data.PUBLIC_STORAGE_PATH),
	};

	mkdirSync(dirname(env.DATABASE_PATH), { recursive: true });
	mkdirSync(env.PUBLIC_STORAGE_PATH, { recursive: true });

	return env;
}
