#!/usr/bin/env just --justfile

# Using Just: https://github.com/casey/just?tab=readme-ov-file#installation

# List all of the available commands.
default:
  just --list


# Upgrade any tooling
upgrade:
	bun update
	bun outdated

# Build the packages
build env="dev":
	bun vite build --mode "{{env}}"

# Deploy the site to Cloudflare Pages
deploy env="staging":
	just build "{{env}}"
	bun wrangler deploy --env "{{env}}"

# Run the app in development mode
dev:
	bun vite dev

# Amazing tool to visualize the app bundle size
bundle:
	npx vite-bundle-visualizer
