#!/usr/bin/env just --justfile

# Using Just: https://github.com/casey/just?tab=readme-ov-file#installation

# List all of the available commands.
default:
  just --list


# Upgrade any tooling
upgrade:
	pnpm self-update
	pnpm update
	pnpm outdated

# Build the packages
build env="dev":
	pnpm vite build --mode "{{env}}"

# Deploy the site to Cloudflare Pages
deploy env="staging":
	just build "{{env}}"
	pnpm wrangler deploy --env "{{env}}"

dev flags="":
	pnpm vite dev {{flags}}
