#!/usr/bin/env just --justfile

# Using Just: https://github.com/casey/just?tab=readme-ov-file#installation

# List all of the available commands.
default:
  just --list


# Upgrade any tooling
upgrade:
	bun update
	bun outdated

# Build the packages
build env="dev":
	bun vite build --mode "{{env}}"

# Deploy the site to Cloudflare Pages
deploy env="staging":
	just build "{{env}}"
	bun wrangler deploy --env "{{env}}"

dev flags="":
	bun vite dev {{flags}}

# Amazing tool to visualize the app bundle size
bundle:
	npx vite-bundle-visualizer
