export type FilePath = {
	path: string;
	mime: string;
};

export type VideoSource = {
	// Single file source or multiple sources with different formats (e.g., WebM, MP4)
	// When multiple sources provided, the first supported format will be used
	paths: string | FilePath[];

	// An image thumbnail for the meme.
	thumbnail: string;

	// CSS object-fit: how the video fits within its container
	// - "contain": scales to fit entirely within container (may have letterbox/pillarbox)
	// - "cover": scales to cover entire container (may crop)
	fit: "contain" | "cover";

	// CSS object-position: where the video is positioned within its container
	// Examples: "center", "bottom", "top left", "50% 75%"
	position: "center" | "bottom" | "top left" | "top right" | "bottom left" | "bottom right" | "right";

	// Chroma key color for greenscreen removal (hex color without #, e.g., "00FF00")
	// Defaults to "00FF00" (pure green) if not specified
	chroma?: string;
};

export type AudioSource = {
	source: string;
	emoji: string;
};

export type Video = {
	element: HTMLVideoElement;
} & Omit<VideoSource, "paths">;

export interface Audio {
	url: string;
	emoji: string;
	// Unfortunately we can't use HTMLAudioElement because iOS requires user interaction to play.
}

export type AV = Video | Audio;

export const AUDIO = {
	"among-us": { source: "among-us.mp3", emoji: "📮" },
	aww: { source: "aww.mp3", emoji: "🥺" },
	brb: { source: "be-right-back.mp3", emoji: "🚶" },
	bluetooth: { source: "bluetooth.mp3", emoji: "📶" },
	bonk: { source: "bonk.mp3", emoji: "🏏" },
	bruh: { source: "bruh.mp3", emoji: "😑" },
	"check-mark": { source: "check-mark.mp3", emoji: "✅" },
	checkout: { source: "checkout.mp3", emoji: "🛒" },
	danger: { source: "danger.mp3", emoji: "⚠️" },
	disappear: { source: "disappear.mp3", emoji: "💨" },
	discord: { source: "discord.mp3", emoji: "💬" },
	error: { source: "error.mp3", emoji: "❌" },
	fbi: { source: "fbi.mp3", emoji: "👮" },
	fart: { source: "fart-reverb.mp3", emoji: "💩" },
	"fitness-gram": { source: "fitness-gram.mp3", emoji: "💪" },
	"hello-there": { source: "hello-there.mp3", emoji: "👋" },
	hub: { source: "hub-intro.mp3", emoji: "🍑" },
	huh: { source: "huh.mp3", emoji: "🤔" },
	incorrect: { source: "incorrect.mp3", emoji: "❌" },
	knock: { source: "knock.mp3", emoji: "🚪" },
	meow: { source: "meow.mp3", emoji: "🐱" },
	"metal-pipe": { source: "metal-pipe.mp3", emoji: "🔧" },
	mlg: { source: "mlg.mp3", emoji: "📢" },
	nut: { source: "nut.mp3", emoji: "🥜" },
	oof: { source: "oof.mp3", emoji: "💀" },
	piuw: { source: "piuw.mp3", emoji: "🔫" },
	ps2: { source: "ps2.mp3", emoji: "🎮" },
	quack: { source: "quack.mp3", emoji: "🦆" },
	rizz: { source: "rizz.mp3", emoji: "😏" },
	spooky: { source: "spooky.mp3", emoji: "💀" },
	stinks: { source: "stinks.mp3", emoji: "💩" },
	suspense: { source: "suspense.mp3", emoji: "😰" },
	uwu: { source: "uwu.mp3", emoji: "🥰" },
	violin: { source: "violin.mp3", emoji: "🎻" },
	boom: { source: "boom.mp3", emoji: "💥" },
	wow: { source: "wow.mp3", emoji: "😮" },
	yay: { source: "yay.mp3", emoji: "🎉" },
} as const satisfies Record<string, AudioSource>;

export const VIDEO = {
	"another-one": {
		paths: [
			{ path: "another-one.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "another-one.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "another-one.png",
		fit: "cover",
		position: "bottom",
	},
	"moments-later": {
		paths: "a-few-moments-later.mp4",
		thumbnail: "a-few-moments-later.png",
		fit: "cover",
		position: "center",
	},
	brb: {
		paths: [
			{ path: "be-right-back.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "be-right-back.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "be-right-back.png",
		fit: "contain",
		position: "center",
	},
	"bing-chilling": {
		paths: [
			{ path: "bing-chilling.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "bing-chilling.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "bing-chilling.png",
		fit: "contain",
		position: "bottom left",
	},
	crying: {
		paths: [
			{ path: "crying.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "crying.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "crying.png",
		fit: "cover",
		position: "center",
	},
	"getting-away-with-it": {
		paths: [
			{ path: "getting-away-with-it.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "getting-away-with-it.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "getting-away-with-it.png",
		fit: "cover",
		position: "center",
	},
	disappointment: {
		paths: [
			{ path: "disappointment.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "disappointment.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "disappointment.png",
		fit: "cover",
		position: "bottom",
	},
	"hello-there": {
		paths: [
			{ path: "hello-there.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "hello-there.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "hello-there.png",
		fit: "cover",
		position: "bottom",
	},
	hackerman: {
		paths: [
			{ path: "hackerman.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "hackerman.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "hackerman.png",
		fit: "contain",
		position: "bottom",
	},
	"aww-shit": {
		paths: [
			{ path: "aww-shit.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "aww-shit.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "aww-shit.png",
		fit: "cover",
		position: "bottom",
	},
	error: {
		paths: [
			{ path: "error.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "error.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "error.png",
		fit: "cover",
		position: "center",
	},
	huh: {
		paths: [
			{ path: "huh.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "huh.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "huh.png",
		fit: "cover",
		position: "center",
		chroma: "00b733",
	},
	kek: {
		paths: [
			{ path: "kekw.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "kekw.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "kekw.png",
		fit: "cover",
		position: "bottom right",
	},
	instagram: {
		paths: [
			{ path: "instagram.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "instagram.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "instagram.png",
		fit: "contain",
		position: "bottom",
	},
	maxwell: {
		paths: [
			{ path: "maxwell.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "maxwell.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "maxwell.png",
		fit: "cover",
		position: "center",
	},
	nice: {
		paths: [
			{ path: "nice.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "nice.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "nice.png",
		fit: "cover",
		position: "bottom right",
	},
	oiia: {
		paths: [
			{ path: "oiia.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "oiia.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "oiia.png",
		fit: "cover",
		position: "center",
	},
	"no-god": {
		paths: [
			{ path: "no-god-no.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "no-god-no.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "no-god-no.png",
		fit: "cover",
		position: "bottom left",
	},
	continued: {
		paths: [
			{ path: "continued.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "continued.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "continued.png",
		fit: "cover",
		position: "bottom left",
	},
	reformed: {
		paths: [
			{ path: "reformed.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "reformed.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "reformed.png",
		fit: "cover",
		position: "bottom",
	},
	"do-it": {
		paths: [
			{ path: "do-it.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "do-it.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "do-it.png",
		fit: "cover",
		position: "bottom",
	},
	thick: {
		paths: [
			{ path: "thick.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "thick.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "thick.png",
		fit: "cover",
		position: "bottom",
	},
	"yeah-baby": {
		paths: [
			{ path: "yeah-baby.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "yeah-baby.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "yeah-baby.png",
		fit: "cover",
		position: "center",
	},
	"thug-life": {
		paths: [
			{ path: "thug-life.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "thug-life.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "thug-life.png",
		fit: "contain",
		position: "center",
	},
	"giga-chad": {
		paths: [
			{ path: "giga-chad.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "giga-chad.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "giga-chad.png",
		fit: "cover",
		position: "center",
	},
	okay: {
		paths: [
			{ path: "okay.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "okay.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "okay.png",
		fit: "contain",
		position: "right",
	},
	// TODO: It should go over the screenshare, not the webcam, and should be in the top right corner.
	// "speedrun": { source: [{ file: "speedrun.webm", mime: 'video/webm; codecs="vp9"' }] },
	"pizza-time": {
		paths: [
			{ path: "pizza-time.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "pizza-time.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "pizza-time.png",
		fit: "cover",
		position: "bottom",
	},
	"stop-it": {
		paths: [
			{ path: "stop-it.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "stop-it.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "stop-it.png",
		fit: "cover",
		position: "bottom",
	},
	"you-died": {
		paths: [
			{ path: "you-died.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "you-died.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "you-died.png",
		fit: "cover",
		position: "center",
	},
	"real-estate": {
		paths: [
			{ path: "real-estate.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "real-estate.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "real-estate.png",
		fit: "cover",
		position: "center",
	},
	waw: {
		paths: [
			{ path: "waw.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "waw.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "waw.png",
		fit: "cover",
		position: "bottom",
	},
	zzz: {
		paths: [
			{ path: "zzz.webm", mime: 'video/webm; codecs="vp9"' },
			{ path: "zzz.mp4", mime: 'video/mp4; codecs="avc1.42E01E"' },
		],
		thumbnail: "zzz.png",
		fit: "cover",
		position: "center",
	},
} as const satisfies Record<string, VideoSource>;

export type AudioName = keyof typeof AUDIO;
export type VideoName = keyof typeof VIDEO;

// Lookup tables for slash commands (without hyphens)
export const AUDIO_LOOKUP: Record<string, AudioName> = {};
export const VIDEO_LOOKUP: Record<string, VideoName> = {};

// Build lookup tables for slash commands without hyphens
for (const [key] of Object.entries(AUDIO)) {
	const lookupKey = key.replace(/-/g, "");
	AUDIO_LOOKUP[lookupKey] = key as AudioName;
}

for (const [key] of Object.entries(VIDEO)) {
	const lookupKey = key.replace(/-/g, "");
	VIDEO_LOOKUP[lookupKey] = key as VideoName;
}

// Popular emojis organized by category - expanded set
export const EMOJI_CATEGORIES = {
	faces: [
		"😀",
		"😃",
		"😄",
		"😁",
		"😂",
		"🤣",
		"😊",
		"😇",
		"🙂",
		"🙃",
		"😉",
		"😌",
		"😍",
		"🥰",
		"😘",
		"😗",
		"😙",
		"😚",
		"☺️",
		"😋",
		"😛",
		"😜",
		"🤪",
		"😝",
		"🤑",
		"🤗",
		"🤭",
		"🤫",
		"🤔",
		"🤐",
		"🤨",
		"😐",
		"😑",
		"😶",
		"😏",
		"😒",
		"🙄",
		"😬",
		"🤥",
		"😌",
		"😔",
		"😪",
		"🤤",
		"😴",
		"😷",
		"🤒",
		"🤕",
		"🤢",
		"🤮",
		"🤧",
		"🥵",
		"🥶",
		"🥴",
		"😵",
		"🤯",
		"🤠",
		"🥳",
		"😎",
		"🤓",
		"🧐",
		"😕",
		"😟",
		"🙁",
		"☹️",
		"😮",
		"😯",
		"😲",
		"😳",
		"🥺",
		"😦",
		"😧",
		"😨",
		"😰",
		"😥",
		"😢",
		"😭",
		"😱",
		"😖",
		"😣",
		"😞",
		"😓",
		"😩",
		"😫",
		"🥱",
		"😤",
		"😡",
		"😠",
		"🤬",
		"😈",
		"👿",
		"💀",
		"☠️",
		"💩",
		"🤡",
		"👹",
		"👺",
		"👻",
		"👽",
		"👾",
		"🤖",
	],
	gestures: [
		"👍",
		"👎",
		"👌",
		"👊",
		"✊",
		"🤛",
		"🤜",
		"🤞",
		"✌️",
		"🤟",
		"🤘",
		"👈",
		"👉",
		"👆",
		"👇",
		"☝️",
		"✋",
		"🤚",
		"🖐",
		"🖖",
		"👋",
		"🤙",
		"💪",
		"🦾",
		"🖕",
		"✍️",
		"🙏",
		"🦶",
		"🦵",
		"🦿",
		"💄",
		"💋",
		"👄",
		"🦷",
		"👅",
		"👂",
		"🦻",
		"👃",
		"👣",
		"👁",
		"👀",
		"🫀",
		"🫁",
		"🧠",
		"🗣",
		"👤",
		"👥",
		"🫂",
		"👶",
		"👧",
		"🧒",
		"👦",
		"👩",
		"🧑",
		"👨",
	],
	hearts: [
		"❤️",
		"🧡",
		"💛",
		"💚",
		"💙",
		"💜",
		"🖤",
		"🤍",
		"🤎",
		"💔",
		"❣️",
		"💕",
		"💞",
		"💓",
		"💗",
		"💖",
		"💘",
		"💝",
		"💟",
	],
	objects: [
		"🎮",
		"🕹",
		"🎯",
		"🎲",
		"🎳",
		"🎪",
		"🎨",
		"🎬",
		"🎤",
		"🎧",
		"🎼",
		"🎵",
		"🎶",
		"🎹",
		"🥁",
		"🎸",
		"🎺",
		"🎷",
		"🪗",
		"🎻",
		"🪕",
		"🔔",
		"🔕",
		"📯",
		"🎙",
		"🎚",
		"🎛",
		"📻",
		"📱",
		"📲",
		"☎️",
		"📞",
		"📟",
		"📠",
		"🔋",
		"🔌",
		"💻",
		"🖥",
		"🖨",
		"⌨️",
		"🖱",
		"🖲",
		"💾",
		"💿",
		"📀",
		"🧮",
		"🎥",
		"🎞",
		"📽",
		"🎬",
		"📺",
		"📷",
		"📸",
		"📹",
		"📼",
		"🔍",
		"🔎",
		"🕯",
		"💡",
		"🔦",
		"🏮",
		"🪔",
		"📔",
		"📕",
		"📖",
		"📗",
		"📘",
		"📙",
		"📚",
		"📓",
		"📒",
		"📃",
		"📜",
		"📄",
		"📰",
		"🗞",
		"📑",
		"🔖",
		"🏷",
		"💰",
		"💴",
		"💵",
		"💶",
		"💷",
		"💸",
		"💳",
		"🧾",
		"💹",
	],
	food: [
		"🍕",
		"🍔",
		"🍟",
		"🌭",
		"🥐",
		"🥖",
		"🥨",
		"🥯",
		"🥞",
		"🧇",
		"🧀",
		"🍖",
		"🍗",
		"🥩",
		"🥓",
		"🍳",
		"🥚",
		"🧈",
		"🥔",
		"🌮",
		"🌯",
		"🥙",
		"🧆",
		"🥘",
		"🍝",
		"🍜",
		"🍲",
		"🍛",
		"🍣",
		"🍱",
		"🥟",
		"🦪",
		"🍤",
		"🍙",
		"🍚",
		"🍘",
		"🍥",
		"🥠",
		"🥮",
		"🍢",
		"🍡",
		"🍧",
		"🍨",
		"🍦",
		"🥧",
		"🧁",
		"🍰",
		"🎂",
		"🍮",
		"🍭",
		"🍬",
		"🍫",
		"🍿",
		"🍩",
		"🍪",
		"🌰",
		"🥜",
		"🍯",
		"🥛",
		"🍼",
		"☕",
		"🫖",
		"🍵",
		"🧃",
		"🥤",
		"🧋",
		"🍶",
		"🍺",
		"🍻",
		"🥂",
		"🍷",
		"🥃",
		"🍸",
		"🍹",
		"🧉",
		"🍾",
		"🧊",
		"🥄",
		"🍴",
		"🍽",
		"🥣",
		"🥡",
		"🥢",
		"🧂",
	],
	animals: [
		"🐶",
		"🐱",
		"🐭",
		"🐹",
		"🐰",
		"🦊",
		"🐻",
		"🐼",
		"🐻‍❄️",
		"🐨",
		"🐯",
		"🦁",
		"🐮",
		"🐷",
		"🐽",
		"🐸",
		"🐵",
		"🙈",
		"🙉",
		"🙊",
		"🐒",
		"🐔",
		"🐧",
		"🐦",
		"🐤",
		"🐣",
		"🐥",
		"🦆",
		"🦅",
		"🦉",
		"🦇",
		"🐺",
		"🐗",
		"🐴",
		"🦄",
		"🐝",
		"🪱",
		"🐛",
		"🦋",
		"🐌",
		"🐞",
		"🐜",
		"🪰",
		"🪲",
		"🪳",
		"🦟",
		"🦗",
		"🕷",
		"🕸",
		"🦂",
		"🐢",
		"🐍",
		"🦎",
		"🦖",
		"🦕",
		"🐙",
		"🦑",
		"🦐",
		"🦞",
		"🦀",
		"🐡",
		"🐠",
		"🐟",
		"🐬",
		"🐳",
		"🐋",
		"🦈",
		"🐊",
		"🐅",
		"🐆",
		"🦓",
		"🦍",
		"🦧",
		"🦣",
		"🐘",
		"🦛",
		"🦏",
		"🐪",
		"🐫",
		"🦒",
		"🦘",
		"🦬",
		"🐃",
		"🐂",
		"🐄",
		"🐎",
		"🐖",
		"🐏",
		"🐑",
		"🦙",
		"🐐",
		"🦌",
		"🐕",
		"🐩",
		"🦮",
		"🐕‍🦺",
		"🐈",
		"🐈‍⬛",
		"🪶",
		"🐓",
		"🦃",
		"🦤",
		"🦚",
		"🦜",
		"🦢",
		"🦩",
		"🕊",
		"🐇",
		"🦝",
		"🦨",
		"🦡",
		"🦫",
		"🦦",
		"🦥",
		"🐁",
		"🐀",
		"🐿",
		"🦔",
	],
	nature: [
		"🌵",
		"🎄",
		"🌲",
		"🌳",
		"🌴",
		"🪵",
		"🌱",
		"🌿",
		"☘️",
		"🍀",
		"🎍",
		"🪴",
		"🎋",
		"🍃",
		"🍂",
		"🍁",
		"🍄",
		"🐚",
		"🪨",
		"🌾",
		"💐",
		"🌷",
		"🌹",
		"🥀",
		"🌺",
		"🌸",
		"🌼",
		"🌻",
		"🌞",
		"🌝",
		"🌛",
		"🌜",
		"🌚",
		"🌕",
		"🌖",
		"🌗",
		"🌘",
		"🌑",
		"🌒",
		"🌓",
		"🌔",
		"🌙",
		"🌎",
		"🌍",
		"🌏",
		"🪐",
		"💫",
		"⭐",
		"🌟",
		"✨",
		"⚡",
		"☄️",
		"💥",
		"🔥",
		"🌪",
		"🌈",
		"☀️",
		"🌤",
		"⛅",
		"🌥",
		"☁️",
		"🌦",
		"🌧",
		"⛈",
		"🌩",
		"🌨",
		"❄️",
		"☃️",
		"⛄",
		"🌬",
		"💨",
		"💧",
		"💦",
		"☔",
		"☂️",
		"🌊",
		"🌫",
	],
	symbols: [
		"💯",
		"🔢",
		"#️⃣",
		"*️⃣",
		"0️⃣",
		"1️⃣",
		"2️⃣",
		"3️⃣",
		"4️⃣",
		"5️⃣",
		"6️⃣",
		"7️⃣",
		"8️⃣",
		"9️⃣",
		"🔟",
		"🔠",
		"🔡",
		"🔤",
		"🆗",
		"🆙",
		"🆒",
		"🆕",
		"🆓",
		"🆖",
		"🔴",
		"🟠",
		"🟡",
		"🟢",
		"🔵",
		"🟣",
		"⚫",
		"⚪",
		"🟤",
		"🔺",
		"🔻",
		"🔸",
		"🔹",
		"🔶",
		"🔷",
		"🔳",
		"🔲",
		"▪️",
		"▫️",
		"◾",
		"◽",
		"◼️",
		"◻️",
		"🟥",
		"🟧",
		"🟨",
		"🟩",
		"🟦",
		"🟪",
		"⬛",
		"⬜",
		"🟫",
		"🔈",
		"🔇",
		"🔉",
		"🔊",
		"🔔",
		"🔕",
		"📣",
		"📢",
		"💬",
		"💭",
		"🗯",
		"♠️",
		"♣️",
		"♥️",
		"♦️",
		"🃏",
		"🎴",
		"🀄",
	],
	sports: [
		"⚽",
		"🏀",
		"🏈",
		"⚾",
		"🥎",
		"🏐",
		"🏉",
		"🥏",
		"🎱",
		"🪀",
		"🏓",
		"🏸",
		"🏒",
		"🏑",
		"🥍",
		"🏏",
		"🪃",
		"🥅",
		"⛳",
		"🪁",
		"🏹",
		"🎣",
		"🤿",
		"🥊",
		"🥋",
		"🎽",
		"🛹",
		"🛼",
		"🛷",
		"⛸",
		"🥌",
		"🎿",
		"⛷",
		"🏂",
		"🪂",
		"🏋️‍♀️",
		"🏋️",
		"🏋️‍♂️",
		"🤼‍♀️",
		"🤼",
		"🤼‍♂️",
		"🤸‍♀️",
		"🤸",
		"🤸‍♂️",
		"⛹️‍♀️",
		"⛹️",
		"⛹️‍♂️",
		"🤺",
		"🤾‍♀️",
		"🤾",
		"🤾‍♂️",
		"🏌️‍♀️",
		"🏌️",
		"🏌️‍♂️",
		"🏇",
		"🧘‍♀️",
		"🧘",
		"🧘‍♂️",
		"🏄‍♀️",
		"🏄",
		"🏄‍♂️",
		"🏊‍♀️",
		"🏊",
		"🏊‍♂️",
		"🤽‍♀️",
		"🤽",
		"🤽‍♂️",
		"🚣‍♀️",
		"🚣",
		"🚣‍♂️",
		"🧗‍♀️",
		"🧗",
		"🧗‍♂️",
		"🚵‍♀️",
		"🚵",
		"🚵‍♂️",
		"🚴‍♀️",
		"🚴",
		"🚴‍♂️",
		"🏆",
		"🥇",
		"🥈",
		"🥉",
		"🏅",
		"🎖",
		"🏵",
		"🎗",
		"🎫",
		"🎟",
		"🎪",
		"🤹‍♀️",
		"🤹",
		"🤹‍♂️",
		"🎭",
		"🩰",
		"🎨",
		"🎬",
		"🎤",
		"🎧",
		"🎼",
		"🎹",
		"🥁",
		"🪘",
		"🎷",
		"🎺",
		"🪗",
		"🎸",
		"🪕",
		"🎻",
		"🎲",
		"♟",
		"🎯",
		"🎳",
		"🎮",
		"🎰",
		"🧩",
	],
	travel: [
		"🚗",
		"🚕",
		"🚙",
		"🚌",
		"🚎",
		"🏎",
		"🚓",
		"🚑",
		"🚒",
		"🚐",
		"🛻",
		"🚚",
		"🚛",
		"🚜",
		"🦯",
		"🦽",
		"🦼",
		"🛴",
		"🚲",
		"🛵",
		"🏍",
		"🛺",
		"🚨",
		"🚔",
		"🚍",
		"🚘",
		"🚖",
		"🚡",
		"🚠",
		"🚟",
		"🚃",
		"🚋",
		"🚞",
		"🚝",
		"🚄",
		"🚅",
		"🚈",
		"🚂",
		"🚆",
		"🚇",
		"🚊",
		"🚉",
		"✈️",
		"🛫",
		"🛬",
		"🛩",
		"💺",
		"🛰",
		"🚀",
		"🛸",
		"🚁",
		"🛶",
		"⛵",
		"🚤",
		"🛥",
		"🛳",
		"⛴",
		"🚢",
		"⚓",
		"🪝",
		"⛽",
		"🚧",
		"🚦",
		"🚥",
		"🚏",
		"🗺",
		"🗿",
		"🗽",
		"🗼",
		"🏰",
		"🏯",
		"🏟",
		"🎡",
		"🎢",
		"🎠",
		"⛲",
		"⛱",
		"🏖",
		"🏝",
		"🏜",
		"🌋",
		"⛰",
		"🏔",
		"🗻",
		"🏕",
		"⛺",
		"🛖",
		"🏠",
		"🏡",
		"🏘",
		"🏚",
		"🏗",
		"🏭",
		"🏢",
		"🏬",
		"🏣",
		"🏤",
		"🏥",
		"🏦",
		"🏨",
		"🏪",
		"🏫",
		"🏩",
		"💒",
		"🏛",
		"⛪",
		"🕌",
		"🕍",
		"🛕",
		"🕋",
		"⛩",
		"🛤",
		"🛣",
		"🗾",
		"🎑",
		"🏞",
		"🌅",
		"🌄",
		"🌠",
		"🎇",
		"🎆",
		"🌇",
		"🌆",
		"🏙",
		"🌃",
		"🌌",
		"🌉",
		"🌁",
	],
} as const;

export const ALL_EMOJIS = Object.values(EMOJI_CATEGORIES).flat();

export function audio(name: AudioName): Audio {
	const source = AUDIO[name];

	return {
		url: new URL(`/meme/${source.source}`, import.meta.env.VITE_APP_URL).toString(),
		emoji: source.emoji,
	};
}

export function video(name: VideoName): Video | undefined {
	const videoSource = VIDEO[name];
	const video = document.createElement("video") as HTMLVideoElement;

	let path: string | undefined;

	if (Array.isArray(videoSource.paths)) {
		// Find the first supported format
		path = videoSource.paths.find((source) => {
			const canPlay = video.canPlayType(source.mime);
			return canPlay === "probably" || canPlay === "maybe";
		})?.path;
	} else {
		path = videoSource.paths;
	}

	if (!path) {
		console.warn(`No supported video format found for meme: ${name}`);
		return undefined;
	}

	// TODO move this element creation elsewhere.
	video.crossOrigin = "anonymous";
	video.src = new URL(`/meme/${path}`, import.meta.env.VITE_APP_URL).toString();
	video.muted = true; // Otherwise autoplay might not work
	video.playsInline = true;
	video.style.objectFit = videoSource.fit || "contain";
	video.style.objectPosition = videoSource.position || "center";

	return { element: video, ...videoSource };
}

// NOTE: We don't cache elements because the browser will.
// Otherwise it would be a pain in the butt to manage if the same meme is played simultaneously.
export function load(name: string): AV | undefined {
	// Make the name lowercase and remove hyphens for lookup
	const lower = name.toLowerCase();
	const key = lower.replace(/-/g, "");

	const v = VIDEO_LOOKUP[key] || (lower as VideoName);
	if (VIDEO[v]) return video(v);

	const a = AUDIO_LOOKUP[key] || (lower as AudioName);
	if (AUDIO[a]) return audio(a);

	return undefined;
}
