name = "api"
main = "src/index.ts"
compatibility_date = "2025-07-11"

account_id = "dd618f5dbd5da77b8296f1613c301f5c"

[dev]
port = 3000

[[d1_databases]]
binding = "DB"
database_name = "api-db-dev"
database_id = "api-db-dev"

[[r2_buckets]]
binding = "PUBLIC"
bucket_name = "api-public-dev"

[vars]
API_URL = "http://localhost:3000"
APP_URL = "http://localhost:1420"
JWT_SECRET = "dev-secret-change-in-production-must-be-32-chars-min"
GOOGLE_CLIENT_ID = "632186286103-6g3knqa8eof9p4bf1ndedgn9r6g68n73.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
DISCORD_CLIENT_ID = "1392633766010294494"
DISCORD_CLIENT_SECRET = "uJRHl-pmOFYHvrViHJdcs2slyTCnoJog"
R2_PUBLIC_URL = ""

[env.staging]
route = { pattern = "api.hang.now", custom_domain = true }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "api-db-staging"
database_id = "b1e6f098-3681-4396-a591-45c7c6a3e25d"

[[env.staging.r2_buckets]]
binding = "PUBLIC"
bucket_name = "api-public-staging"

[env.staging.vars]
API_URL = "https://api.hang.now"
APP_URL = "https://hang.now"
JWT_SECRET = "stage_v1_s3mi$3cret_Mr2@Tk#xNw8VzQdYiLgPeC4u"
GOOGLE_CLIENT_ID = "1093943946174-915g0a9jpu7gih5emghmtabhge29qgg2.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
DISCORD_CLIENT_ID = "1392629623812259940"
DISCORD_CLIENT_SECRET = "bps97yMNROIhml22zeJIySo0CP6ZBAYF"
R2_PUBLIC_URL = "https://r2.hang.now"

[env.live]
route = { pattern = "api.hang.live", custom_domain = true }

[[env.live.d1_databases]]
binding = "DB"
database_name = "api-db-live"
database_id = "065d2e39-134d-464b-a030-27a23bf2bea0"

[[env.live.r2_buckets]]
binding = "PUBLIC"
bucket_name = "api-public-live"

[env.live.vars]
API_URL = "https://api.hang.live"
APP_URL = "https://hang.live"
JWT_SECRET = "prod_v1_t0p$3cret_7GmX9@qLcWzR!Yk#hUfE2AvbD"
GOOGLE_CLIENT_ID = "632186286103-p5k3rhlsq1bgkku7dluko4nlv4ca4hao.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
DISCORD_CLIENT_ID = "1389725440020840548"
DISCORD_CLIENT_SECRET = "5aFK47Syy2nPGzgwrzRa4shQZWYQEwHo"
R2_PUBLIC_URL = "https://r2.hang.live"
