#!/usr/bin/env just --justfile

# Using Just: https://github.com/casey/just?tab=readme-ov-file#installation

# List all of the available commands.
default:
  just --list

dev:
	pnpm i
	pnpm wrangler types
	pnpm wrangler d1 migrations apply DB --local
	pnpm wrangler dev --var "RELAY_SECRET:$(cat ../moq/rs/dev/root.jwk)"

build:
	pnpm i
	pnpm wrangler types
	pnpm run build

deploy env="staging": build
	pnpm wrangler d1 migrations apply DB --env "{{env}}" --remote
	pnpm wrangler deploy --env "{{env}}"
