#!/usr/bin/env just --justfile

# Using Just: https://github.com/casey/just?tab=readme-ov-file#installation

# List all of the available commands.
default:
  just --list

dev:
	pnpm i
	pnpm wrangler types
	pnpm wrangler d1 migrations apply DB --local
	# Generate SSL certificates for API development
	mkdir -p dev
	mkcert -cert-file dev/api-cert.pem -key-file dev/api-key.pem localhost api.hang.dev
	pnpm wrangler dev --var "RELAY_SECRET:$(cat ../moq/rs/dev/root.jwk)" --host api.hang.dev --local-protocol https --https-key-path dev/api-key.pem --https-cert-path dev/api-cert.pem

build:
	pnpm i
	pnpm wrangler types
	pnpm run build

deploy env="staging": build
	pnpm wrangler d1 migrations apply DB --env "{{env}}" --remote
	pnpm wrangler deploy --env "{{env}}"
